# -*- coding: utf-8 -*-
"""StormDetector.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LE2MD5438nnGMNS3fNtItZQI9V6V5XoR
"""

from google.colab import drive
drive.mount('/content/drive')

! git clone https://github.com/ultralytics/yolov5.git

! pip install -r yolov5/requirements.txt

cp /content/drive/MyDrive/FIAP/2026/storm.yaml yolov5/data/

!python yolov5/train.py --data storm.yaml --weights yolov5s.pt --img 640 --epochs 180

import os
import subprocess

def get_latest_train_run_folder():
    subfolders = [f.path for f in os.scandir('yolov5/runs/train') if f.is_dir()]
    latest_folder = max(subfolders, key=os.path.getctime, default=None)
    return latest_folder

latest_run = get_latest_train_run_folder()
result = subprocess.run(f'python yolov5/detect.py --weights {latest_run}/weights/best.pt --img 640 --source drive/MyDrive/FIAP/2026/test/ --data yolov5/data/storm.yaml', shell=True, capture_output=True, text=True)
if latest_run:
    # COMANDO
    result = subprocess.run(f'python yolov5/detect.py --weights {latest_run}/weights/best.pt --img 640 --source drive/MyDrive/FIAP/2026/test/ --data yolov5/data/storm.yaml', shell=True, capture_output=True, text=True)
    print(result.stdout)
    print(result.stderr)
else:
    print("Não foi possível encontrar a pasta de treinamento mais recente.")